### ISSUE TITLE
Migration to 16.0

### ISSUE THREAD

**Issue by zuher83** [it-projects-llc/saas-addons#142]
**Thank you** for your **excellent work** for this contribution
Are you planning a migration to 16.0 and if so can we help?
I have already started to migrate... to version 16.0 but I will probably need the help of the community
Can you open a new 16.0 branch to contribute, or is that not in the goals?

Thanks

**Comment by zuher83** [comment]
I migrated to 16.0 and it works fine 😍. I'm testing again this week. I'm thinking of using it in production mode in 15 days...
I think it will be **important** to create a new repo with all dependents apps necessary to install on the child databases with by def "get_mandatory_modules(self)"
eg: 
- access_limit_max_users, 
- access_limit_records_number, 
- auth_quick,
- database_block _(I completely rewrote the architecture of the module so as not to depend on "web_responsive" and have a total block of access to the instance)_
- database_expiration
- database_limit_size
...
My fork repo [https://github.com/zuher83/saas-addons](url)
As soon as the tests are finished I will propose a pull request to migrate 16.0

**Features:**
- I will also work to make the UI more friendly for administrators 😎 (kanban views, portal ...)
- Create a monitoring and alerting system
- Email templates
- ...
In my opinion, it is also necessary to review some aspects of architecture...
I will keep you informed of the progress in this thread (I feel less lonely) 😊

(Спасибо) thanks it-projects-llc team @em230418 🙏😉

**Comment by ilmir-k** [comment]
Hello @zuher83 
Thank you for your contribution. We appreciate it.
We'll let you know once prepare 16.0 branch to be able to PR the updates.

**Comment by flotho** [comment]
hi @zuher83 , 
any PR to propose so that we'll be able to help with @gaelTorrecillas

**Comment by zuher83** [comment]
Ok @flotho, as soon as I can, I make pull request after cleaning the repo

**Comment by killday** [comment]
Hi @zuher83 does your repo works with v16.0? 
I'll give it a go today and try to contribute as much as I can.
Thanks

**Comment by zuher83** [comment]
Sorry I wasn't available lately, but I'll try to contribute in a few days. Yes it works well for me at the moment

**Comment by gaelTorrecillas** [comment]
/Hello,

@zuher83 I tested your branch, thanks for your work.

- config : ok
I configurated saas with an instance type "remote instance"
- saas template created a db template : ok
- I created an instance : KO

When I tried to create an instance, job  'saas.db.create_db' returned : 
```

Traceback (most recent call last):
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/OCA-queue/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/OCA-queue/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/OCA-queue/queue_job/job.py", line 517, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas/models/saas_db.py", line 36, in create_db
    self.state = 'done'
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/fields.py", line 1324, in __set__
    records.write({self.name: write_value})
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas/models/saas_db.py", line 64, in write
    self.refresh_data()
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas/models/saas_db.py", line 77, in refresh_data
    record.operator_id._signal_changes(record.name)
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas_operator_remote/models/saas_operator.py", line 163, in _signal_changes
    response = jsonrpc(
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas_operator_remote/models/saas_operator.py", line 29, in jsonrpc
    raise Exception(message)
Exception: ==========
REMOTE INSTANCE TRACEBACK
==========
Traceback (most recent call last):
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/http.py", line 1591, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/http.py", line 1618, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/http.py", line 1822, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/DEV/_ProjetsOdoo/odoo_16/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas_cluster_simple/controllers/main.py", line 25, in wrap
    return f(*args, **kw)
  File "/home/DEV/Odoo_Server_And_Libs/Libs_16.0/saas-addons/saas_cluster_simple/controllers/main.py", line 35, in run_cluster_method
    return method(**kw)
TypeError: signal_changes() got an unexpected keyword argument 'db_name' 
```

blocking further execution. However in postgresql, the database is well created. I can't determine the origin of the problem.

Did you have this problem?
