### ISSUE TITLE
Odoo Instance Creation Problem via Virtual Store

### ISSUE THREAD

**Issue by jlromualdo** [it-projects-llc/saas-addons#147]
Hi everyone,

I would like to ask for help with a problem I am facing when creating Odoo instances via the Virtual Store.

I am using Odoo v15 on Ubuntu 20.04. When I create an instance as an administrator, it works perfectly. However, when I create one via the Virtual Store, in trial mode, it does not work.

I have tried creating one with a template and with an App, and the error is the same. The system creates the base that the client requested, but it remains in draft. When I access the "Job Queue" menu, 
I see that the process has failed.

contract.contract._create_build	contract.contract
Failed	13/09/2023 10:01:10		
0,00	

ValueError	Invalid field res.users.is_excluded_from_limiting in leaf ('is_excluded_from_limiting', '=', False)	b1843627-7ac7-4d9e-ac45-3f4347dd63be

PS. I added the code as per "Update auth_signup.py to fix #126 #132"
But the error persists

Error:

Exception Information
Exception:ValueError
Traceback (most recent call last):
  File "/opt/wsolut/addons_queue-saas/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/opt/wsolut/addons_queue-saas/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/opt/wsolut/addons_queue-saas/queue_job/job.py", line 517, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/wsolut/addons-saas/saas_apps_signup/models/contract_contract.py", line 147, in _create_build
    template_operator.create_db(
  File "/opt/wsolut/addons-saas/saas/models/saas_template.py", line 238, in create_db
    build.create_db(
  File "/opt/wsolut/addons-saas/saas/models/saas_db.py", line 32, in create_db
    self.state = 'done'
  File "/opt/wsolut/odoo/fields.py", line 1242, in __set__
    records.write({self.name: write_value})
  File "/opt/wsolut/addons-saas/saas_limit_max_users/models/saas_db.py", line 26, in write
    return super(SaasDb, self).write(vals)
  File "/opt/wsolut/addons-saas/saas_domain_names/models/saas_db.py", line 39, in write
    res = super(SaasDb, self).write(vals)
  File "/opt/wsolut/addons-saas/saas_build_admin/models/saas_db.py", line 21, in write
    return super(SaasDb, self).write(vals)
  File "/opt/wsolut/addons-saas/saas/models/saas_db.py", line 59, in write
    self.refresh_data()
  File "/opt/wsolut/addons-saas/saas/models/saas_db.py", line 66, in refresh_data
    vals = record.read_values_from_build()
  File "/opt/wsolut/addons-saas/saas_apps_signup/models/saas_db.py", line 36, in read_values_from_build
    vals = super(SaasDb, self).read_values_from_build()
  File "/opt/wsolut/addons-saas/saas_limit_max_users/models/saas_db.py", line 59, in read_values_from_build
    users_count=self.execute_kw(
  File "/opt/wsolut/addons-saas/saas/models/saas_db.py", line 81, in execute_kw
    return self.operator_id.build_execute_kw(self, model, method, args, kwargs)
  File "/opt/wsolut/addons-saas/saas/models/saas_operator.py", line 151, in build_execute_kw
    return self._build_execute_kw(build.name, model, method, args, kwargs)
  File "/opt/wsolut/addons-saas/saas/models/saas_operator.py", line 145, in _build_execute_kw
    return cluster.execute_kw(db_name, model, method, args, kwargs)
  File "/opt/wsolut/addons-saas/saas_cluster_simple/main.py", line 126, in execute_kw
    return execute(db_name, SUPERUSER_ID, model, method, *args, **kwargs)
  File "/opt/wsolut/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/wsolut/addons-saas/saas_cluster_simple/main.py", line 175, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/wsolut/odoo/service/model.py", line 160, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/opt/wsolut/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/wsolut/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/wsolut/odoo/models.py", line 1787, in search_count
    res = self.search(args, count=True)
  File "/opt/wsolut/odoo/models.py", line 1810, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/wsolut/odoo/addons/base/models/res_users.py", line 559, in _search
    return super(Users, self)._search(args, offset=offset, limit=limit, order=order, count=count,
  File "/opt/wsolut/odoo/models.py", line 4711, in _search
    query = self._where_calc(args)
  File "/opt/wsolut/odoo/models.py", line 4467, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/wsolut/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/opt/wsolut/odoo/osv/expression.py", line 654, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
ValueError: Invalid field res.users.is_excluded_from_limiting in leaf ('is_excluded_from_limiting', '=', False)

**Comment by killday** [comment]
Hi,
Check if you have installed this addon: access_limit_max_users
if not install it
